name: Java CI with Maven

<<<<<<< HEAD
on:
  push:
    branches:  
      - develop
<<<<<<< HEAD
      - main
=======
>>>>>>> develop

=======
on: [push]
>>>>>>> 9cf7cedbad155167067b8062c9c3489853632b04
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        java-package: jdk
        cache: maven
        
    - name: Build with Maven
<<<<<<< HEAD
      run: mvn -B install --file pom.xml
      #run: mvn -B clean package jacoco:report
=======
      #run: mvn -B install --file pom.xml
      run: mvn -B clean package jacoco:report
>>>>>>> develop
            
    - name: Coveralls
      run: mvn -B coveralls:report --define repoToken=${{ secrets.COVERALLS_TOKEN }}
